# Generated by Django 2.2.2 on 2019-07-15 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-date_published', '-date_created']},
        ),
    ]
